// Generated by https://quicktype.io

import { IResponse } from "@/@types/fetch-types";
import VideoMeta from "../_components/video-meta";

async function getVideoURL() {
  const response = await fetch("http://localhost:5000/api/v1/videos", {
    cache: "no-cache",
  });
  if (!response.ok) {
    throw new Error(response.statusText);
  }
  const data: IResponse = await response.json();

  return data;
}

export default async function Videos() {
  const videos = await getVideoURL();
  return (
    <>
      {videos.data.videos.map((video) => {
        return (
          <>
            <h1 className="text-sm font-bold text-foreground py-1">
              {video.name}
            </h1>
            <div className="mb-4 flex gap-2 justify-between" key={video.name}>
              <div className="border aspect-video basis-1/3">
                <video
                  src={video.processed.url}
                  className="w-full h-full"
                  controls
                ></video>
              </div>
              <VideoMeta
                metaURL={video.source.meta}
                processedMetaURL={video.processed.meta}
              />
            </div>
          </>
        );
      })}
    </>
  );
}
